spring:
  application:
    name: SampleNF

mvf4ms:
  version: 3.0.0
  dependencies:
    - name: dependency1
      dependence:
        - id: pay
          serviceName: SampleAlipay
          patternUrl: /pay
          slas:
            - 3
            - 4

server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://{REGISTRY_IP}:{REGISTRY_PORT}/eureka
